name: gh-backup

on:
  push:
    paths: ['gh-backup/**']
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    permissions:
      packages: write
    with:
      path: gh-backup
