name: sqlite-backup

on:
  push:
    paths: ['sqlite-backup/**']
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    permissions:
      packages: write
    with:
      path: sqlite-backup
